# Site settings
author: Jung Lee
title: CLI Data Gem Project
header-img: img/home-bg.png
email: lee.jung.s95@gmail.com
copyright_name: Jung Lee
description: > # this means to ignore newlines until "baseurl:"
  Easy or Difficult? It depends.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Shirkirai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
